let ham_burger=document.getElementById(`ham_burger`);
let mobile_menu=document.getElementById(`mobile_menu`);
let body=document.querySelectorAll(`body`)[0];
let menu_btn_1=document.getElementById(`Menu_btn_1`);
let menu_btn_2=document.getElementById(`Menu_btn_2`);
let menu_btn_3=document.getElementById(`Menu_btn_3`);
let menu_btn_4=document.getElementById(`Menu_btn_4`);
let dish_1=document.querySelectorAll(`.starter`);
let dish_2=document.querySelectorAll(`.salads`);
let dish_3=document.querySelectorAll(`.speciall`);
let  S_btn_1=document.getElementById(`S_btn_1`);
let  S_btn_2=document.getElementById(`S_btn_2`);
let  S_btn_3=document.getElementById(`S_btn_3`);
let  S_btn_4=document.getElementById(`S_btn_4`);
let  S_btn_5=document.getElementById(`S_btn_5`);
let S_box_1=document.getElementById(`S_box_1`);
let S_box_2=document.getElementById(`S_box_2`);
let S_box_3=document.getElementById(`S_box_3`);
let S_box_4=document.getElementById(`S_box_4`);
let S_box_5=document.getElementById(`S_box_5`);
ham_burger.addEventListener(`click`,()=>{mobile_menu.classList.toggle(`hidden`)});
let uls=document.querySelectorAll(`ul`);
uls.forEach(e=>{e.addEventListener(`click`,()=>{mobile_menu.classList.add(`hidden`)})});
setInterval(()=>{if(body.clientWidth>'1004'){mobile_menu.classList.add(`hidden`)}else{}});
menu_btn_1.addEventListener(`click`,()=>{
dish_1.forEach(e=>{e.classList.remove('hidden')});
dish_2.forEach(e=>{e.classList.remove('hidden')});
dish_3.forEach(e=>{e.classList.remove('hidden')});
menu_btn_1.classList.add(`text-yellow-600`);
menu_btn_2.classList.remove(`text-yellow-600`);
menu_btn_3.classList.remove(`text-yellow-600`);
menu_btn_4.classList.remove(`text-yellow-600`)});
menu_btn_2.addEventListener(`click`,()=>{
dish_1.forEach(e=>{e.classList.remove('hidden')});
dish_2.forEach(e=>{e.classList.add('hidden')});
dish_3.forEach(e=>{e.classList.add('hidden')});
menu_btn_1.classList.remove(`text-yellow-600`);
menu_btn_2.classList.add(`text-yellow-600`);
menu_btn_3.classList.remove(`text-yellow-600`);
menu_btn_4.classList.remove(`text-yellow-600`)});
menu_btn_3.addEventListener(`click`,()=>{
dish_1.forEach(e=>{e.classList.add('hidden')});
dish_2.forEach(e=>{e.classList.remove('hidden')});
dish_3.forEach(e=>{e.classList.add('hidden')});
menu_btn_1.classList.remove(`text-yellow-600`);
menu_btn_2.classList.remove(`text-yellow-600`);
menu_btn_3.classList.add(`text-yellow-600`);
menu_btn_4.classList.remove(`text-yellow-600`)});
menu_btn_4.addEventListener(`click`,()=>{
dish_1.forEach(e=>{e.classList.add('hidden')});
dish_2.forEach(e=>{e.classList.add('hidden')});
dish_3.forEach(e=>{e.classList.remove('hidden')});
menu_btn_1.classList.remove(`text-yellow-600`);
menu_btn_2.classList.remove(`text-yellow-600`);
menu_btn_3.classList.remove(`text-yellow-600`);
menu_btn_4.classList.add(`text-yellow-600`)});
S_btn_1.addEventListener(`click`,()=>{
S_btn_1.classList.add(`bg-yellow-600`);
S_btn_1.classList.add(`text-stone-900`);
S_btn_1.classList.remove(`hover:text-yellow-600`);
S_btn_2.classList.remove(`bg-yellow-600`);
S_btn_2.classList.remove(`text-stone-900`);
S_btn_2.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`bg-yellow-600`);
S_btn_3.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`text-stone-900`);
S_btn_4.classList.remove(`bg-yellow-600`);
S_btn_4.classList.remove(`text-stone-900`);
S_btn_4.classList.add(`hover:text-yellow-600`);
S_btn_5.classList.remove(`bg-yellow-600`);
S_btn_5.classList.remove(`text-stone-900`);
S_btn_5.classList.add(`hover:text-yellow-600`);
S_box_1.classList.remove(`hidden`);
S_box_1.classList.add(`flex`);
S_box_2.classList.add(`hidden`);
S_box_2.classList.remove(`flex`);
S_box_3.classList.add(`hidden`);
S_box_3.classList.remove(`flex`);
S_box_4.classList.add(`hidden`);
S_box_4.classList.remove(`flex`);
S_box_5.classList.add(`hidden`);
S_box_5.classList.remove(`flex`);})
S_btn_2.addEventListener(`click`,()=>{;
S_btn_1.classList.remove(`bg-yellow-600`);
S_btn_1.classList.remove(`text-stone-900`);
S_btn_1.classList.add(`hover:text-yellow-600`);
S_btn_2.classList.add(`bg-yellow-600`);
S_btn_2.classList.add(`text-stone-900`);
S_btn_2.classList.remove(`hover:text-yellow-600`);
S_btn_3.classList.remove(`bg-yellow-600`);
S_btn_3.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`text-stone-900`);
S_btn_4.classList.remove(`bg-yellow-600`);
S_btn_4.classList.remove(`text-stone-900`);
S_btn_4.classList.add(`hover:text-yellow-600`);
S_btn_5.classList.remove(`bg-yellow-600`);
S_btn_5.classList.remove(`text-stone-900`);
S_btn_5.classList.add(`hover:text-yellow-600`);
S_box_1.classList.add(`hidden`);
S_box_1.classList.remove(`flex`);
S_box_2.classList.remove(`hidden`);
S_box_2.classList.add(`flex`);
S_box_3.classList.add(`hidden`);
S_box_3.classList.remove(`flex`);
S_box_4.classList.add(`hidden`);
S_box_4.classList.remove(`flex`);
S_box_5.classList.add(`hidden`);
S_box_5.classList.remove(`flex`);})
S_btn_3.addEventListener(`click`,()=>{;
S_btn_1.classList.remove(`bg-yellow-600`);
S_btn_1.classList.remove(`text-stone-900`);
S_btn_1.classList.add(`hover:text-yellow-600`);
S_btn_2.classList.remove(`bg-yellow-600`);
S_btn_2.classList.remove(`text-stone-900`);
S_btn_2.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.add(`bg-yellow-600`);
S_btn_3.classList.remove(`hover:text-yellow-600`);
S_btn_3.classList.add(`text-stone-900`);
S_btn_4.classList.remove(`bg-yellow-600`);
S_btn_4.classList.remove(`text-stone-900`);
S_btn_4.classList.add(`hover:text-yellow-600`);
S_btn_5.classList.remove(`bg-yellow-600`);
S_btn_5.classList.remove(`text-stone-900`);
S_btn_5.classList.add(`hover:text-yellow-600`);
S_box_1.classList.add(`hidden`);
S_box_1.classList.remove(`flex`);
S_box_2.classList.add(`hidden`);
S_box_2.classList.remove(`flex`);
S_box_3.classList.remove(`hidden`);
S_box_3.classList.add(`flex`);
S_box_4.classList.add(`hidden`);
S_box_4.classList.remove(`flex`);
S_box_5.classList.add(`hidden`);
S_box_5.classList.remove(`flex`);})
S_btn_4.addEventListener(`click`,()=>{;
S_btn_1.classList.remove(`bg-yellow-600`);
S_btn_1.classList.remove(`text-stone-900`);
S_btn_1.classList.add(`hover:text-yellow-600`);
S_btn_2.classList.remove(`bg-yellow-600`);
S_btn_2.classList.remove(`text-stone-900`);
S_btn_2.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`bg-yellow-600`);
S_btn_3.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`text-stone-900`);
S_btn_4.classList.add(`bg-yellow-600`);
S_btn_4.classList.add(`text-stone-900`);
S_btn_4.classList.remove(`hover:text-yellow-600`);
S_btn_5.classList.remove(`bg-yellow-600`);
S_btn_5.classList.remove(`text-stone-900`);
S_btn_5.classList.add(`hover:text-yellow-600`);
S_box_1.classList.add(`hidden`);
S_box_1.classList.remove(`flex`);
S_box_2.classList.add(`hidden`);
S_box_2.classList.remove(`flex`);
S_box_3.classList.add(`hidden`);
S_box_3.classList.remove(`flex`);
S_box_4.classList.remove(`hidden`);
S_box_4.classList.add(`flex`);
S_box_5.classList.add(`hidden`);
S_box_5.classList.remove(`flex`);})
S_btn_5.addEventListener(`click`,()=>{;
S_btn_1.classList.remove(`bg-yellow-600`);
S_btn_1.classList.remove(`text-stone-900`);
S_btn_1.classList.add(`hover:text-yellow-600`);
S_btn_2.classList.remove(`bg-yellow-600`);
S_btn_2.classList.remove(`text-stone-900`);
S_btn_2.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`bg-yellow-600`);
S_btn_3.classList.add(`hover:text-yellow-600`);
S_btn_3.classList.remove(`text-stone-900`);
S_btn_4.classList.remove(`bg-yellow-600`);
S_btn_4.classList.remove(`text-stone-900`);
S_btn_4.classList.add(`hover:text-yellow-600`);
S_btn_5.classList.add(`bg-yellow-600`);
S_btn_5.classList.add(`text-stone-900`);
S_btn_5.classList.remove(`hover:text-yellow-600`);
S_box_1.classList.add(`hidden`);
S_box_1.classList.remove(`flex`);
S_box_2.classList.add(`hidden`);
S_box_2.classList.remove(`flex`);
S_box_3.classList.add(`hidden`);
S_box_3.classList.remove(`flex`);
S_box_4.classList.add(`hidden`);
S_box_4.classList.remove(`flex`);
S_box_5.classList.remove(`hidden`);
S_box_5.classList.add(`flex`);})
